"""initial_schema

Revision ID: 56005649f40b
Revises: 
Create Date: 2026-04-08 23:17:08.037144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56005649f40b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxonomy_candidate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_label', sa.String(), nullable=False),
    sa.Column('dimension', sa.Enum('category', 'style', 'color', 'scene', 'detail', name='dimensionenum'), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_label')
    )
    op.create_table('taxonomy_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('dimension', sa.Enum('category', 'style', 'color', 'scene', 'detail', name='dimensionenum'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['taxonomy_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', 'buyer', name='userrole'), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('original_uri', sa.String(), nullable=False),
    sa.Column('display_uri', sa.String(), nullable=False),
    sa.Column('thumb_uri', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('feature_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['image_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_embedding',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('model_ver', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.execute("ALTER TABLE asset_embedding ADD COLUMN vector vector(768)")
    op.execute("CREATE INDEX ON asset_embedding USING ivfflat (vector vector_cosine_ops) WITH (lists = 100)")
    op.create_table('asset_tag',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('ai', 'human', name='tagsource'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['taxonomy_node.id'], ),
    sa.PrimaryKeyConstraint('asset_id', 'node_id')
    )
    op.create_table('lookbook',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('cover_asset_id', sa.UUID(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lookbook_access',
    sa.Column('lookbook_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lookbook_id'], ['lookbook.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('lookbook_id', 'user_id')
    )
    op.create_table('lookbook_item',
    sa.Column('lookbook_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['lookbook_id'], ['lookbook.id'], ),
    sa.PrimaryKeyConstraint('lookbook_id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lookbook_item')
    op.drop_table('lookbook_access')
    op.drop_table('lookbook')
    op.drop_table('asset_tag')
    op.drop_table('asset_embedding')
    op.drop_table('asset')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('taxonomy_node')
    op.drop_table('taxonomy_candidate')
    op.drop_table('image_group')
    # ### end Alembic commands ###
